[package]
name = "secrets-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
secrets-core = { path = "../secrets-core" }
secrets-crypto = { path = "../secrets-crypto" }
serde_json.workspace = true
sqlx.workspace = true
uuid.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio.workspace = true

