[package]
name = "secrets-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes-gcm.workspace = true
base64.workspace = true
getrandom.workspace = true
serde.workspace = true
secrets-core = { path = "../secrets-core" }
serde_json.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[lints]
workspace = true

