//! `b10x-domain-graph/1` documents from the compiled ESS model (`ess specify compile --format json`).
use anyhow::{Context, Result, bail};
use serde_json::{Map, Value, json};

/// Recorded in each document's `domain.source`, since JSON carries no comment.
pub const SOURCE: &str = "generated by secrets-docs from spec/ (ess specify compile); do not edit";

fn text<'a>(value: &'a Value, key: &str) -> Result<&'a str> {
    value[key]
        .as_str()
        .with_context(|| format!("compiled model: `{key}` is not a string in {value}"))
}

fn strings(value: &Value) -> Vec<Value> {
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter(|item| item.is_string())
                .cloned()
                .collect()
        })
        .unwrap_or_default()
}

/// The last segment of a fully qualified name.
fn short(name: &str) -> &str {
    name.rsplit('.').next().unwrap_or(name)
}

/// A type reference as the graph shows it: `TurnId`, `integer`, `Optional<decimal>`.
pub fn type_name(reference: &Value) -> Result<String> {
    let kind = text(reference, "kind")?;
    match kind {
        "primitive" => Ok(text(reference, "name")?.to_owned()),
        "declared" => Ok(short(text(reference, "name")?).to_owned()),
        // `{"kind": "map", "key": "string", "value": <type reference>}`: the key is a primitive name.
        "map" => {
            let key = match &reference["key"] {
                Value::String(key) => key.clone(),
                key => type_name(key)?,
            };
            Ok(format!("Map<{key}, {}>", type_name(&reference["value"])?))
        }
        _ => {
            let Some(of) = reference.get("of") else {
                bail!("compiled model: unsupported type reference {reference}");
            };
            let mut wrapper = kind.to_owned();
            wrapper[..1].make_ascii_uppercase();
            Ok(format!("{wrapper}<{}>", type_name(of)?))
        }
    }
}

fn field(value: &Value) -> Result<Value> {
    Ok(json!({"name": text(value, "name")?, "type": type_name(&value["type_ref"])?}))
}

fn lifecycle(value: &Value) -> Result<Value> {
    let mut out = Map::new();
    out.insert("initial".into(), json!(text(value, "initial")?));
    out.insert("states".into(), Value::Array(strings(&value["states"])));
    let terminal = strings(&value["terminal"]);
    if !terminal.is_empty() {
        out.insert("terminal".into(), Value::Array(terminal));
    }
    if let Some(transitions) = value["transitions"].as_array() {
        let transitions = transitions
            .iter()
            .map(|transition| {
                Ok(json!({
                    "name": text(transition, "name")?,
                    "from": strings(&transition["from"]),
                    "to": text(transition, "to")?,
                }))
            })
            .collect::<Result<Vec<_>>>()?;
        if !transitions.is_empty() {
            out.insert("transitions".into(), Value::Array(transitions));
        }
    }
    Ok(Value::Object(out))
}

/// One domain of the compiled model as a `b10x-domain-graph/1` document.
pub fn domain_graph(model: &Value, domain: &str) -> Result<Value> {
    let declared = &model["domains"][domain];
    let naming = &declared["naming"];
    let mut header = Map::new();
    header.insert("id".into(), json!(domain));
    for (key, source) in [("display", "display"), ("summary", "summary")] {
        if let Some(value) = naming[source].as_str() {
            header.insert(key.into(), json!(value));
        }
    }
    header.insert("system".into(), json!(text(model, "system")?));
    header.insert("source".into(), json!(SOURCE));

    let mut names: Vec<&str> = declared["entities"]
        .as_array()
        .with_context(|| format!("compiled model: domain {domain} lists no entities"))?
        .iter()
        .filter_map(Value::as_str)
        .collect();
    names.sort_unstable();

    let mut entities = Vec::new();
    let mut relations = Vec::new();
    for name in names {
        let entity = &model["entities"][name];
        let identity = &entity["identity"];
        let mut out = Map::new();
        out.insert("id".into(), json!(name));
        out.insert("name".into(), json!(short(name)));
        out.insert("identity".into(), field(identity)?);
        let fields = entity["fields"]
            .as_array()
            .map(|fields| fields.iter().map(field).collect::<Result<Vec<_>>>())
            .transpose()?
            .unwrap_or_default();
        out.insert("fields".into(), Value::Array(fields));
        if entity["lifecycle"].is_object() {
            out.insert("lifecycle".into(), lifecycle(&entity["lifecycle"])?);
        }
        entities.push(Value::Object(out));
        for relation in entity["relations"].as_array().into_iter().flatten() {
            let mut edge = Map::new();
            edge.insert("from".into(), json!(name));
            edge.insert("to".into(), json!(text(relation, "target")?));
            edge.insert("name".into(), json!(text(relation, "name")?));
            edge.insert("kind".into(), json!(text(relation, "kind")?));
            edge.insert("cardinality".into(), json!(text(relation, "cardinality")?));
            if let Some(via) = relation["via"].as_str() {
                edge.insert("via".into(), json!(via));
            }
            relations.push(Value::Object(edge));
        }
    }
    Ok(json!({
        "format": "b10x-domain-graph/1",
        "domain": Value::Object(header),
        "entities": entities,
        "relations": relations,
    }))
}

/// Every domain of the compiled model, keyed by domain id.
pub fn domain_graphs(model: &Value) -> Result<Vec<(String, Value)>> {
    let domains = model["domains"]
        .as_object()
        .context("compiled model has no domains")?;
    domains
        .keys()
        .map(|domain| Ok((domain.clone(), domain_graph(model, domain)?)))
        .collect()
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    fn model() -> Value {
        json!({
            "system": "secrets",
            "domains": {"secrets.custody": {
                "naming": {"display": "Run", "summary": "One run."},
                "entities": ["secrets.custody.Turn", "secrets.custody.Session"]
            }},
            "entities": {
                "secrets.custody.Session": {
                    "identity": {"name": "session_id", "type_ref": {"kind": "declared", "name": "secrets.custody.SessionId"}},
                    "fields": [{"name": "confidence", "type_ref": {"kind": "optional", "of": {"kind": "primitive", "name": "decimal"}}}],
                    "lifecycle": {"initial": "Active", "states": ["Active", "Closed"], "terminal": ["Closed"],
                        "transitions": [{"name": "close", "from": ["Active"], "to": "Closed"}]},
                    "relations": [{"name": "turns", "kind": "owns", "target": "secrets.custody.Turn", "cardinality": "many", "via": "session_id"}]
                },
                "secrets.custody.Turn": {
                    "identity": {"name": "turn_id", "type_ref": {"kind": "declared", "name": "secrets.custody.TurnId"}},
                    "fields": [{"name": "index", "type_ref": {"kind": "primitive", "name": "integer"}}],
                    "lifecycle": {"initial": "Taken", "states": ["Taken"], "terminal": ["Taken"]},
                    "relations": []
                }
            }
        })
    }

    #[test]
    fn a_domain_becomes_a_sorted_graph_with_short_type_names() {
        let graphs = domain_graphs(&model()).unwrap();
        assert_eq!(graphs.len(), 1);
        let (id, graph) = &graphs[0];
        assert_eq!(id, "secrets.custody");
        assert_eq!(graph["format"], "b10x-domain-graph/1");
        assert_eq!(graph["domain"]["display"], "Run");
        assert_eq!(graph["domain"]["source"], SOURCE);
        let names: Vec<_> = graph["entities"]
            .as_array()
            .unwrap()
            .iter()
            .map(|entity| entity["id"].as_str().unwrap())
            .collect();
        assert_eq!(names, ["secrets.custody.Session", "secrets.custody.Turn"]);
        let session = &graph["entities"][0];
        assert_eq!(
            session["identity"],
            json!({"name": "session_id", "type": "SessionId"})
        );
        assert_eq!(session["fields"][0]["type"], "Optional<decimal>");
        assert_eq!(session["lifecycle"]["transitions"][0]["to"], "Closed");
        assert_eq!(
            graph["relations"][0],
            json!({"from": "secrets.custody.Session", "to": "secrets.custody.Turn", "name": "turns",
                   "kind": "owns", "cardinality": "many", "via": "session_id"})
        );
    }

    #[test]
    fn an_unknown_type_reference_is_refused() {
        assert!(type_name(&json!({"kind": "mystery"})).is_err());
        assert_eq!(
            type_name(&json!({"kind": "list", "of": {"kind": "declared", "name": "a.b.C"}}))
                .unwrap(),
            "List<C>"
        );
    }
}
