#![forbid(unsafe_code)]
//! Generates the derivable part of the documentation site as Markdown under
//! `website/docs/reference/`, checks it for drift, and binds a built site to its source commit.
//! The site build itself is Docusaurus.
//!
//! The generated reference is the ESS domain reference: Markdown pages from
//! `ess generate --kind docs`, and one `b10x-domain-graph/1` document per domain from
//! `ess specify compile`. The HTTP contract stays `docs/openapi.json`, which the service embeds.
mod graph;
mod routes;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, bail, ensure};
use clap::{Parser, Subcommand};

/// The line every generated Markdown page carries directly after its front matter.
const HEADER: &str = "<!-- generated by secrets-docs, do not edit -->";
/// The same line in an MDX page, where HTML comments are not allowed.
const MDX_HEADER: &str = "{/* generated by secrets-docs, do not edit */}";
/// Where the ESS reference pages land, relative to the repository root.
const ESS_REFERENCE: &str = "website/docs/reference/ess";
/// Where the domain graphs land, relative to the repository root.
const ESS_DATA: &str = "website/data/ess";
/// Every documentation page, generated or written by hand, relative to the repository root.
const DOCS: &str = "website/docs";

/// Whether `line` matches `^:::[a-z]+ +\S`: an admonition whose title is not in brackets, which
/// Docusaurus prints as raw text.
fn is_raw_admonition(line: &str) -> bool {
    let Some(rest) = line.strip_prefix(":::") else {
        return false;
    };
    let kind = rest.bytes().take_while(u8::is_ascii_lowercase).count();
    let rest = &rest[kind..];
    let spaces = rest.bytes().take_while(|b| *b == b' ').count();
    kind > 0
        && spaces > 0
        && rest[spaces..]
            .chars()
            .next()
            .is_some_and(|c| !c.is_whitespace())
}

/// `file:line` of every raw admonition title in the Markdown and MDX pages under `dir`.
fn raw_admonitions(dir: &Path) -> Result<Vec<String>> {
    let mut found = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
        .collect::<Result<_, _>>()?;
    entries.sort_by_key(|entry| entry.path());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            found.extend(raw_admonitions(&path)?);
        } else if path
            .extension()
            .is_some_and(|ext| ext == "md" || ext == "mdx")
        {
            for (n, line) in fs::read_to_string(&path)?.lines().enumerate() {
                if is_raw_admonition(line) {
                    found.push(format!("{}:{}", path.display(), n + 1));
                }
            }
        }
    }
    Ok(found)
}

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the Secrets documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate website/docs/reference/ from the repository, or check it for drift.
    Generate {
        /// Write nothing; fail when a generated page is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
        /// The `ess` executable.
        #[arg(long, default_value = "ess")]
        ess: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` and the route
    /// inventory `.well-known/b10x-routes.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// The project-site publication record for one build of the `/secrets/` site.
fn site_manifest(commit: &str) -> Result<String> {
    ensure!(
        commit.len() == 40
            && commit.bytes().all(|b| b.is_ascii_hexdigit())
            && commit != "0".repeat(40),
        "commit must be a nonzero full Git revision"
    );
    Ok(format!(
        "{{\n  \"baseUrl\": \"/secrets/\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"secrets\",\n  \"schema\": \"b10x-project-site/v1\"\n}}"
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    ensure!(
        site.join("index.html").is_file(),
        "{} holds no built site",
        site.display()
    );
    let inventory = routes::inventory(site, commit)?;
    fs::create_dir_all(site.join(".well-known"))?;
    fs::write(site.join(".well-known/b10x-site.json"), manifest)
        .context("writing site provenance")?;
    fs::write(site.join(".well-known/b10x-routes.json"), inventory)
        .context("writing the route inventory")?;
    fs::write(site.join(".nojekyll"), "")?;
    Ok(())
}

/// Pages keyed by file name, in the order they are written.
type Pages = BTreeMap<String, String>;

/// Strip the leading HTML comment `ess generate` writes, returning the rest.
fn strip_ess_banner(page: &str) -> Result<&str> {
    let rest = page
        .strip_prefix("<!--")
        .context("ess page does not open with its provenance comment")?;
    let end = rest
        .find("-->")
        .context("ess provenance comment is not closed")?;
    Ok(rest[end + 3..].trim_start_matches('\n'))
}

/// The H1 title and the first paragraph after it.
fn title_and_summary(body: &str) -> Result<(String, String)> {
    let mut lines = body.lines();
    let title = lines
        .next()
        .and_then(|line| line.strip_prefix("# "))
        .context("ess page does not open with a level-one heading")?
        .trim()
        .to_owned();
    let summary = lines
        .skip_while(|line| line.trim().is_empty())
        .take_while(|line| !line.trim().is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    ensure!(!summary.is_empty(), "ess page {title} has no summary");
    Ok((title, summary))
}

fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn front_matter(title: &str, label: &str, description: &str, header: &str) -> String {
    format!(
        "---\ntitle: {}\nsidebar_label: {}\ndescription: {}\n---\n\n{header}\n\n",
        yaml_string(title),
        yaml_string(label),
        yaml_string(description),
    )
}

/// One domain page of `ess generate --kind docs`, rewritten as a site page.
fn domain_page(source: &str) -> Result<(String, String, String)> {
    let body = strip_ess_banner(source)?;
    let (title, summary) = title_and_summary(body)?;
    let body = body
        .replace(
            "[Back to the index](../index.md)",
            "[All domains](./index.mdx)",
        )
        .replace("](../crossings.md)", "](./crossings.md)")
        .replace("`ess generate`", "`task docs-generate`");
    ensure!(
        !body.contains("](../"),
        "ess page {title} links outside the generated domain pages"
    );
    let page = front_matter(
        &format!("{title} domain"),
        &title,
        &format!("ESS reference for the {title} domain, generated from the specification."),
        HEADER,
    ) + &body;
    Ok((title, summary, page))
}

/// The system's type crossings page of `ess generate --kind docs`, which domain pages link to.
fn crossings_page(source: &str) -> Result<String> {
    let body = strip_ess_banner(source)?;
    let (title, summary) = title_and_summary(body)?;
    let body = body
        .replace(
            "[Back to the index](index.md)",
            "[All domains](./index.mdx)",
        )
        .replace("`ess generate`", "`task docs-generate`");
    ensure!(
        !body.contains("](../") && !body.contains("](index.md)"),
        "ess page {title} links outside the generated pages"
    );
    let description = summary.split(". ").next().unwrap_or(&summary).to_owned() + ".";
    Ok(front_matter(&title, &title, &description, HEADER) + &body)
}

/// One domain as the index lists it.
struct DomainEntry {
    page: String,
    graph: String,
    title: String,
    summary: String,
}

/// The reference index: one `<DomainGraph>` per domain, then a link to its full page.
fn index_page(domains: &[DomainEntry]) -> String {
    let mut page = front_matter(
        "ESS specification",
        "ESS specification",
        "The Secrets specification, domain by domain, generated from spec/ in the repository.",
        MDX_HEADER,
    );
    for (n, domain) in domains.iter().enumerate() {
        page.push_str(&format!(
            "import domainGraph{n} from '@site/data/ess/{}';\n",
            domain.graph
        ));
    }
    page.push_str("\n# ESS specification\n\n");
    page.push_str(
        "Secrets is specified in ESS. This page and the domain pages below are generated from the \
         repository's `spec/` directory by `secrets-docs`: the graphs from `ess specify compile`, \
         the pages from `ess generate --kind docs`. They change when the specification changes, \
         and `task check` fails if they fall behind it.\n\n\
         `custody` is retrofitted from the shipped service and every declaration cites its source; \
         a conformance suite runs it against the real HTTP router and PostgreSQL store. `storage` \
         is the planned model of named, scoped secrets over several backends, and no code \
         implements it yet.\n",
    );
    for (n, domain) in domains.iter().enumerate() {
        page.push_str(&format!(
            "\n## {title}\n\n{summary}\n\n<DomainGraph data={{domainGraph{n}}} title=\"{title}\" />\n\n\
             [Read the {title} domain in full](./{file})\n",
            title = domain.title,
            summary = domain.summary,
            file = domain.page,
        ));
    }
    page
}

/// Generated files: directory relative to the repository root, then file name, then content.
type Outputs = BTreeMap<&'static str, Pages>;

fn run(ess: &Path, args: &[&std::ffi::OsStr]) -> Result<Vec<u8>> {
    let output = Command::new(ess)
        .args(args)
        .output()
        .with_context(|| format!("running {}", ess.display()))?;
    if !output.status.success() {
        bail!(
            "{} {} failed: {}",
            ess.display(),
            args.iter()
                .map(|arg| arg.to_string_lossy())
                .collect::<Vec<_>>()
                .join(" "),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(output.stdout)
}

/// Run `ess` and build every generated file of the site.
fn ess_outputs(root: &Path, ess: &Path) -> Result<Outputs> {
    let spec = root.join("spec");
    let model: serde_json::Value = serde_json::from_slice(&run(
        ess,
        &[
            "specify".as_ref(),
            "compile".as_ref(),
            "--path".as_ref(),
            spec.as_os_str(),
            "--format".as_ref(),
            "json".as_ref(),
        ],
    )?)
    .context("parsing the compiled ESS model")?;
    let mut data = Pages::new();
    for (domain, graph) in graph::domain_graphs(&model)? {
        let name = format!("{}.domain-graph.json", domain.replace('.', "-"));
        data.insert(name, serde_json::to_string_pretty(&graph)? + "\n");
    }

    let scratch = std::env::temp_dir().join(format!("secrets-docs-{}", std::process::id()));
    if scratch.exists() {
        fs::remove_dir_all(&scratch)?;
    }
    let result = (|| {
        run(
            ess,
            &[
                "generate".as_ref(),
                "--kind".as_ref(),
                "docs".as_ref(),
                "--path".as_ref(),
                spec.as_os_str(),
                "--out".as_ref(),
                scratch.as_os_str(),
            ],
        )?;
        let dir = scratch.join("docs/domains");
        let mut files: Vec<_> = fs::read_dir(&dir)
            .with_context(|| format!("reading {}", dir.display()))?
            .collect::<Result<_, _>>()?;
        files.sort_by_key(|entry| entry.file_name());
        let mut pages = Pages::new();
        let mut index = Vec::new();
        for entry in files {
            let name = entry.file_name().to_string_lossy().into_owned();
            let Some(stem) = name.strip_suffix(".md") else {
                continue;
            };
            let graph = format!("{stem}.domain-graph.json");
            ensure!(
                data.contains_key(&graph),
                "ess page {name} has no domain in the compiled model"
            );
            let (title, summary, page) = domain_page(&fs::read_to_string(entry.path())?)?;
            index.push(DomainEntry {
                page: name.clone(),
                graph,
                title,
                summary,
            });
            pages.insert(name, page);
        }
        ensure!(!index.is_empty(), "ess generated no domain pages");
        ensure!(
            index.len() == data.len(),
            "ess generated {} domain pages for {} domains",
            index.len(),
            data.len()
        );
        pages.insert("index.mdx".to_owned(), index_page(&index));
        let crossings = scratch.join("docs/crossings.md");
        if crossings.is_file() {
            pages.insert(
                "crossings.md".to_owned(),
                crossings_page(&fs::read_to_string(crossings)?)?,
            );
        }
        Ok(pages)
    })();
    let _ = fs::remove_dir_all(&scratch);
    Ok(Outputs::from([(ESS_REFERENCE, result?), (ESS_DATA, data)]))
}

/// Every difference between the expected files and the files in `dir`.
fn drift(expected: &Pages, dir: &Path) -> Result<Vec<String>> {
    let mut actual = Pages::new();
    if dir.exists() {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().into_owned();
            actual.insert(name, fs::read_to_string(entry.path())?);
        }
    }
    let mut problems = Vec::new();
    for (name, content) in expected {
        match actual.get(name) {
            None => problems.push(format!("missing {name}")),
            Some(found) if found != content => problems.push(format!("stale or edited {name}")),
            Some(_) => {}
        }
    }
    for name in actual.keys().filter(|name| !expected.contains_key(*name)) {
        problems.push(format!("not generated {name}"));
    }
    Ok(problems)
}

fn main() -> Result<()> {
    match Cli::parse().command {
        Action::Generate { check, root, ess } => {
            let outputs = ess_outputs(&root, &ess)?;
            for (relative, files) in &outputs {
                let dir = root.join(relative);
                if check {
                    let problems = drift(files, &dir)?;
                    if !problems.is_empty() {
                        bail!(
                            "{relative} has drifted ({}); run `task docs-generate`",
                            problems.join(", ")
                        );
                    }
                    println!("{relative}: {} generated files current", files.len());
                    if relative == &ESS_REFERENCE {
                        let raw = raw_admonitions(&root.join(DOCS))?;
                        if !raw.is_empty() {
                            bail!(
                                "raw admonition titles (write `:::kind[Title]`): {}",
                                raw.join(", ")
                            );
                        }
                        println!("{DOCS}: no raw admonition titles");
                    }
                } else {
                    if dir.exists() {
                        fs::remove_dir_all(&dir)?;
                    }
                    fs::create_dir_all(&dir)?;
                    for (name, content) in files {
                        fs::write(dir.join(name), content)?;
                    }
                    println!("{relative}: wrote {} files", files.len());
                }
            }
        }
        Action::Provenance { site, commit } => {
            write_provenance(&site, &commit)?;
            println!("{}: bound to {commit}", site.display());
        }
    }
    Ok(())
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    const SAMPLE: &str = "<!--\ngenerated from secrets v1\ndo not edit: regenerate with `ess generate`\n-->\n\n# Run\n\nOne model session.\nArguments for one action.\n\n`secrets.custody` is one of secrets' bounded contexts. [Back to the index](../index.md).\n\nDo not edit this file; regenerate it with `ess generate`.\n";

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("secrets-docs-test-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn domain_pages_carry_the_header_and_no_ess_banner() {
        let (title, summary, page) = domain_page(SAMPLE).unwrap();
        assert_eq!(title, "Run");
        assert_eq!(summary, "One model session. Arguments for one action.");
        assert!(page.starts_with("---\ntitle: \"Run domain\"\n"));
        assert!(page.contains(&format!("---\n\n{HEADER}\n\n# Run\n")));
        assert!(!page.contains("generated from secrets v1"));
        assert!(page.contains("[All domains](./index.mdx)"));
        assert!(page.contains("`task docs-generate`"));
    }

    #[test]
    fn links_out_of_the_domain_set_are_refused() {
        let leaking = SAMPLE.replace("One model session.", "See [topology](../topology.md).");
        assert!(domain_page(&leaking).is_err());
        let crossing = SAMPLE.replace("One model session.", "See [crossings](../crossings.md).");
        assert!(
            domain_page(&crossing)
                .unwrap()
                .2
                .contains("[crossings](./crossings.md)")
        );
        assert!(domain_page("# Run\n\nNo banner.\n").is_err());
    }

    #[test]
    fn index_renders_one_graph_per_domain_under_the_header() {
        let page = index_page(&[DomainEntry {
            page: "secrets-custody.md".into(),
            graph: "secrets-custody.domain-graph.json".into(),
            title: "Run".into(),
            summary: "One session.".into(),
        }]);
        assert!(page.contains(MDX_HEADER));
        assert!(!page.contains("<!--"));
        assert!(page.contains(
            "import domainGraph0 from '@site/data/ess/secrets-custody.domain-graph.json';"
        ));
        assert!(page.contains("<DomainGraph data={domainGraph0} title=\"Run\" />"));
        assert!(page.contains("[Read the Run domain in full](./secrets-custody.md)"));
    }

    #[test]
    fn provenance_names_the_commit_and_refuses_a_bad_one() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let manifest = site_manifest(commit).unwrap();
        assert!(manifest.contains(&format!("\"commit\": \"{commit}\"")));
        assert!(manifest.contains("\"schema\": \"b10x-project-site/v1\""));
        assert!(manifest.contains("\"baseUrl\": \"/secrets/\""));
        assert!(site_manifest("e86f43d").is_err());
        assert!(site_manifest(&"0".repeat(40)).is_err());
        assert!(site_manifest(&format!("{}\"", &commit[..39])).is_err());

        let site = scratch("provenance");
        assert!(write_provenance(&site, commit).is_err());
        fs::write(site.join("index.html"), "").unwrap();
        write_provenance(&site, commit).unwrap();
        let written = fs::read_to_string(site.join(".well-known/b10x-site.json")).unwrap();
        assert_eq!(written, manifest);
        fs::remove_dir_all(site).unwrap();
    }

    #[test]
    fn raw_admonition_titles_are_found_and_bracketed_ones_pass() {
        for raw in [
            ":::caution Planned",
            ":::note  These thresholds",
            ":::info Decided design",
        ] {
            assert!(is_raw_admonition(raw), "{raw}");
        }
        for fine in [
            ":::caution[Planned]",
            ":::",
            ":::note",
            ":::note ",
            "::: note Title",
            ":::Note Title",
            " :::note Title",
        ] {
            assert!(!is_raw_admonition(fine), "{fine}");
        }

        let dir = scratch("admonitions");
        fs::create_dir_all(dir.join("concepts")).unwrap();
        fs::write(dir.join("index.md"), ":::caution[Bootstrap]\nok\n:::\n").unwrap();
        fs::write(
            dir.join("concepts/a.mdx"),
            "text\n:::caution Planned\n:::\n",
        )
        .unwrap();
        fs::write(dir.join("notes.txt"), ":::caution Planned\n").unwrap();
        let found = raw_admonitions(&dir).unwrap();
        assert_eq!(found.len(), 1);
        assert!(found[0].ends_with("concepts/a.mdx:2"), "{found:?}");
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn drift_names_missing_edited_and_stray_pages() {
        let dir = scratch("drift");
        let mut expected = Pages::new();
        expected.insert("a.md".into(), "A\n".into());
        expected.insert("b.md".into(), "B\n".into());
        assert_eq!(
            drift(&expected, &dir).unwrap(),
            ["missing a.md", "missing b.md"]
        );
        fs::write(dir.join("a.md"), "A\n").unwrap();
        fs::write(dir.join("b.md"), "B, edited by hand\n").unwrap();
        fs::write(dir.join("c.md"), "C\n").unwrap();
        assert_eq!(
            drift(&expected, &dir).unwrap(),
            ["stale or edited b.md", "not generated c.md"]
        );
        fs::write(dir.join("b.md"), "B\n").unwrap();
        fs::remove_file(dir.join("c.md")).unwrap();
        assert!(drift(&expected, &dir).unwrap().is_empty());
        fs::remove_dir_all(dir).unwrap();
    }
}
