[package]
name = "secrets-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "secrets"
path = "src/main.rs"

[dependencies]
axum.workspace = true
clap.workspace = true
secrets-auth = { path = "../secrets-auth" }
secrets-core = { path = "../secrets-core" }
secrets-crypto = { path = "../secrets-crypto" }
secrets-http = { path = "../secrets-http" }
secrets-postgres = { path = "../secrets-postgres" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

