import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// Pages under docs/reference/ and files under data/ess/ are generated by `secrets-docs generate`;
// everything else is written by hand.
const config: Config = {
  title: 'Secrets',
  tagline: 'Encrypted, tenant-scoped custody of the credentials workloads use for people.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  url: 'https://beyond10x.github.io',
  baseUrl: '/secrets/',

  organizationName: 'beyond10x',
  projectName: 'secrets',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/secrets/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'Secrets',
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/http-api', label: 'HTTP API', position: 'left'},
        {to: '/docs/reference/ess', label: 'Specification', position: 'left'},
        {to: '/docs/status', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/secrets', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/docs/'},
            {label: 'Getting started', to: '/docs/getting-started'},
            {label: 'Security model', to: '/docs/security-model'},
            {label: 'HTTP API', to: '/docs/http-api'},
            {label: 'ESS specification', to: '/docs/reference/ess'},
            {label: 'Status', to: '/docs/status'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Source', href: 'https://github.com/beyond10x/secrets'},
            {label: 'OpenAPI 3.1', href: 'https://github.com/beyond10x/secrets/blob/main/docs/openapi.json'},
            {label: 'Security policy', href: 'https://github.com/beyond10x/secrets/blob/main/SECURITY.md'},
          ],
        },
      ],
      copyright: 'A beyond10x project. Secrets · Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json', mark: 'S'});
