import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['index', 'getting-started', 'status'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: ['security-model', 'authentication'],
    },
    {
      type: 'category',
      label: 'Use and run',
      collapsed: false,
      items: ['http-api', 'rust-client', 'operations'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
